FROM python:3.13-slim
WORKDIR /app
# Create a non-root user to run the application
RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser

COPY ./client_api ./client_api
COPY ./common ./common
COPY ./OpenAI ./OpenAI

# Install dependencies
RUN pip install --no-cache-dir -r ./client_api/req.txt 
RUN pip install --no-cache-dir -r ./OpenAI/req.txt

# && \
RUN pip install ./common 
    # && \
    #chown -R appuser:appgroup /app

# Change ownership of the application directory to the non-root user
USER appuser

# run the application
CMD ["uvicorn", "client_api.main:app", "--host", "0.0.0.0", "--port", "8000"]