[pytest]
testpaths =
    tests/backend/classification
    tests/backend/client_api
    tests/backend/common
    tests/backend/gmail
    tests/backend/openai
    tests/backend/shared_worker_library
    tests/backend/supabase
pythonpath = .
asyncio_mode = auto
addopts =
    --strict-markers
    -p no:cacheprovider
    --cov=client_api
    --cov=common
    --cov=shared_worker_library
    --cov=classification
    --cov=gmail
    --cov=OpenAI
    --cov=supabase
    --cov-branch
    --cov-report=term-missing
    --cov-report=json
