import { render } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { ResumePdfPreview } from './ResumePdfPreview';

vi.mock('@/pages/settings/provider/settingsContext', () => ({ useSettings: () => ({ theme: 'light' }) }));
vi.mock('react-markdown', () => ({ default: (props: any) => <div data-testid="markdown">{props.children}</div> }));
vi.mock('framer-motion', () => ({ motion: { div: 'div', p: 'div', span: 'div', button: 'button', input: 'input' }, AnimatePresence: ({children}: any) => <>{children}</> }));
vi.mock('@hello-pangea/dnd', () => ({
    DragDropContext: ({children}: any) => <div data-testid="dnd-context">{children}</div>,
    Droppable: ({children}: any) => children({ droppableProps: {}, innerRef: vi.fn(), placeholder: null }),
    Draggable: ({children}: any) => children({ draggableProps: {}, dragHandleProps: {}, innerRef: vi.fn() })
}));
vi.mock('lucide-react', () => new Proxy({}, { get: () => () => <div data-testid="icon" /> }));

describe('ResumePdfPreview', () => {
    it('renders without crashing', () => {
        const props = {
            isLightMode: true,
            canvasViewportRef: { current: document.createElement('div') },
            chatScrollShadow: { top: false, bottom: false },
            setFocusedField: vi.fn(),
            chatContainerRef: { current: null },
            chatInputRef: { current: null },
            resumeDocumentContentRef: { current: null },
            canvasViewportRef: { current: document.createElement('div') },
            chatScrollShadow: { top: false, bottom: false },
            setFocusedField: vi.fn(),
            chatContainerRef: { current: null },
            chatInputRef: { current: null },
            resumeDocumentContentRef: { current: null },
            resumeData: { contact: {}, summary: '', experiences: [], education: [], skills: [] },
            data: { resumeData: { contact: {}, summary: '', experiences: [], education: [], skills: [] } },
            data: { resumeData: { contact: {}, summary: '', experiences: [], education: [], skills: [] } },
            formatting: { paperMetrics: { printName: 'A4' } },
            paperMetrics: {},
            currentResumeFormatting: { paperMetrics: { printName: 'A4' } },
            chatMessages: [],
            filteredResumes: [],
            headerContactRows: [],
            chatInput: '',
            searchQuery: '',
            zoomPercent: 100,
            zoomMode: 'fit',
            pageSize: 'letter',
            paperLayoutFormat: 'standard',
            resumeName: 'Test',
            activeResumeId: '1',
            isMaster: false,
            isDraft: false,
            loadingSave: false,
            isPdfPreviewOpen: false,
            isGeneratingPdfPreview: false,
            isLeftRailCollapsed: false,
            isRightRailCollapsed: false,
            isPageStyleShelfOpen: false,
            isPageStyleShelfCompact: false,
            resumeChromeRootClass: '',
            resumeChromeBackground: '',
            headerShellStyle: {},
            railShellStyle: {},
            rightRailShellStyle: {},
            toolbarSurfaceStyle: {},
            shelfSurfaceStyle: {},
            railTitleClass: '',
            railTitleStyle: {},
            railHeaderRowClass: '',
            headerActionButtonClass: '',
            headerActionIconClass: '',
            documentToolButtonClass: '',
            shelfControlLabelClass: '',
            shelfSegmentGroupClass: '',
            shelfSegmentButtonClass: '',
            shelfSegmentIndicatorClass: '',
            shelfStepperButtonClass: '',
            shelfStepperControlClass: '',
            shelfStepperLabelClass: '',
            shelfStepperValueClass: '',
            shelfStepperRowClass: '',
            documentSectionGapStyle: {},
            inputStyleClass: '',
            boldInputClass: '',
            compactFitMetaInputClass: '',
            compactFitDateInputClass: '',
            contactInputClass: '',
            resumeDividerClass: '',
            headerMarginAddClass: '',
            experienceMarginAddClass: '',
            experienceMarginImproveClass: '',
            experienceMarginClearClass: '',
            experienceMarginDeleteClass: '',
            summaryMarginImproveClass: '',
            summaryCurrentRewriteClass: '',
            contactFieldStyle: {},
            documentTextStyle: {},
            sectionHeadingClass: '',
            sectionHeadingStyle: {},
            renderOverlayInput: () => null,
            renderRewriteActionButtons: () => null,
            getDynamicInputStyle: () => ({}),
            getSuggestionReviewClass: () => '',
            resume: { id: '1', name: 'Test' },
            isDeleting: false,
            title: 'Test',
            isActive: false,
            onClick: vi.fn(),
            children: <div>Child</div>,
            value: '',
            onChange: vi.fn(),
            onFocus: vi.fn(),
            onBlur: vi.fn(),
            className: '',
            style: {},
            onCancel: vi.fn(),
            onConfirm: vi.fn(),
            closePageStyleShelf: vi.fn(),
            openPdfPreview: vi.fn(),
        } as any;
        const { container } = render(<ResumePdfPreview {...props} />);
        expect(container).toBeTruthy();
    });
});
