export const SETTINGS_KEYS = {
  THEME: "APP_THEME",
  TEXT_SCALE: "TEXT_SCALE",
  MOTION: "MOTION_PREFERENCE",
  CONTRAST: "CONTRAST_LEVEL",
  NAVIGATION_BEHAVIOR: "NAVIGATION_BEHAVIOR",
  REVIEW_BEHAVIOR: "REVIEW_BEHAVIOR",
  PRIMARY_COLUMN_BEHAVIOR: "PRIMARY_COLUMN_BEHAVIOR",
  SELECTED_PRIMARY_COLUMN: "SELECTED_PRIMARY_COLUMN",
} as const;
