export const SETTINGS_KEYS = {
  THEME: "APP_THEME",
  TEXT_SCALE: "TEXT_SCALE",
  MOTION: "MOTION_PREFERENCE",
  CONTRAST: "CONTRAST_LEVEL",
  NAVIGATION_BEHAVIOR: "NAVIGATION_BEHAVIOR",
} as const;
